### ISSUE TITLE
Mod no longer works on newer verions (1.20+)

### ISSUE THREAD

**Issue by pjt0720** [ReillyGregorio/FasterTools#2]
Game will crash when joining a world.

**Comment by pjt0720** [comment]
[Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoSuchMethodError: 'net.minecraft.class_2540 net.minecraft.class_2540.method_10794(net.minecraft.class_2487)'
	at org.cloudwarp.fastertools.FTEventHandler.lambda$registerEvents$0(FTEventHandler.java:19) ~[fastertools-1.4.0-1.19.1.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-3.0.11+bff13c85a0-598efcd3ddea0f2c.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:59) ~[fabric-networking-api-v1-3.0.11+bff13c85a0-598efcd3ddea0f2c.jar:?]
	at net.minecraft.class_3324.handler$zik000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:2504) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:195) ~[client-intermediary.jar:?]
	at net.minecraft.class_8610.method_52408(class_8610.java:128) ~[client-intermediary.jar:?]
	at net.minecraft.class_8736.method_53043(class_8736.java:20) ~[client-intermediary.jar:?]
	at net.minecraft.class_8736.method_11054(class_8736.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:778) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:163) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:760) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:754) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:139) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:739) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:263) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
